### PR TITLE
support mathStmt

### PR DESCRIPTION
**Pull request by m-kashani**

### CODE REVIEW

**Comment by dcamper** [comment]
It is not clear to me if the following SELECT statements are supported (or if they are even within the scope of this change):

SELECT myNumberField + 1 FROM foo;
SELECT myNumField1 + myNumField2 FROM  foo;

Are those types of operations within a SELECT supported?

**Comment by m-kashani** [comment]
> Are those types of operations within a SELECT supported?

These are just the basic arithmetic operations. You are right we are not supporting it for select statements just yet.

as an example: for input.hsql
```
import %.demods;
customers = demods.ds;

SELECT customersid + 1 FROM Customers;
```
The parse tree shoots error.
image

Where demoDS.ecl is :
```
export demoDS:= module 
    export rec := {
        integer customerid,string customername,string contactName,string address,string city ,string postalcode,string country
    };
    export ds := DATASET([
        {1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin' ,'12209' ,'Germany'},
        {2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitucion 2222', 'Mexico D.F.', '05021' ,'Mexico'},
        {3, 'Antonio Moreno Taquería', 'Antonio Moreno',' Mataderos 2312',' México D.F.' ,'05023' ,'Mexico'},
        {4, 'Around the Horn' ,'Thomas Hardy', '120 Hanover Sq.',' London' ,'WA1 1DP' ,'UK'},
        {5, 'Berglunds snabbköp' ,'Christina Berglund', 'Berguvsvägen 8 ','Luleå','S-958 22' ,'Sweden'}
    ],rec);

end;

// CustomerID CustomerName ContactName Address City PostalCode Country
```

**Comment by dcamper** [comment]
@BaharF Do you think math statements within a SELECT should be supported within this issue?  Or is that a separate issue?

**Comment by BaharF** [comment]
I created a separate ticket to implement math statement within SELECT or other functionalities. Let's continue with this ticket supporting stand-alone math.

**Review by dcamper — APPROVED** [review]

**Pull request merged**
